name: regression tests

on: [pull_request]

jobs:
  module-1:
    name: module 1 tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: cd server
    - run: ls   
    - run: npm ci
    - run: npm run regression
      env:
        CI: true
